

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0x10001 = Integer(0x10001)
from Crypto.Util.number import long_to_bytes
n,c = [int(i.split("= ")[_sage_const_1 ]) for i in open("output.txt", 'r').read().split("\n")]
p,q=[i[_sage_const_0 ] for i in list(factor(n))]
e=_sage_const_0x10001 
phi=(p-_sage_const_1 )*(q-_sage_const_1 )
d=pow(e,-_sage_const_1 ,phi)
print(long_to_bytes(pow(c,d,n)).decode())

