services:
  printf1:
    privileged: true
    image: "magpiesctf2025/pwn-printf1:latest"
    restart: unless-stopped
    ports:
      - 14001:6201
    networks:
      - magpiesctf2025
  printf2:
    privileged: true
    image: "magpiesctf2025/pwn-printf2:latest"
    restart: unless-stopped
    ports:
      - 14002:6201
    networks:
      - magpiesctf2025
  overflow1:
    privileged: true
    image: "magpiesctf2025/pwn-overflow1:latest"
    restart: unless-stopped
    ports:
      - 14003:6201
    networks:
      - magpiesctf2025
  overflow2:
    privileged: true
    image: "magpiesctf2025/pwn-overflow2:latest"
    restart: unless-stopped
    ports:
      - 14004:6201
    networks:
      - magpiesctf2025
  ret2libc1:
    privileged: true
    image: "magpiesctf2025/pwn-ret2libc1:latest"
    restart: unless-stopped
    ports:
      - 14005:6201
    networks:
      - magpiesctf2025
  ret2libc2:
    privileged: true
    image: "magpiesctf2025/pwn-ret2libc2:latest"
    restart: unless-stopped
    ports:
      - 14006:6201
    networks:
      - magpiesctf2025
  # expert1:
  #   privileged: true
  #   image: "magpiesctf2025/pwn-expert1:latest"
  #   restart: unless-stopped
  #   ports:
  #     - 14007:6201
  #   networks:
  #     - magpiesctf2025

networks:
  magpiesctf2025:
    driver: bridge
