services:
  printf1:
    privileged: true
    container_name: "printf1"
    build: ./printf1/src/
    restart: unless-stopped
    ports:
      - 4001:6201
    networks:
      - magpiesctf2025
  printf2:
    privileged: true
    container_name: "printf2"
    build: ./printf2/src/
    restart: unless-stopped
    ports:
      - 4002:6201
    networks:
      - magpiesctf2025
  overflow1:
    privileged: true
    container_name: "overflow1"
    build: ./overflow1/src/
    restart: unless-stopped
    ports:
      - 4003:6201
    networks:
      - magpiesctf2025
  overflow2:
    privileged: true
    container_name: "overflow2"
    build: ./overflow2/src/
    restart: unless-stopped
    ports:
      - 4004:6201
    networks:
      - magpiesctf2025
  ret2win1:
    privileged: true
    container_name: "ret2win1"
    build: ./ret2win1/src/
    restart: unless-stopped
    ports:
      - 4005:6201
    networks:
      - magpiesctf2025
  ret2win2:
    privileged: true
    container_name: "ret2win2"
    build: ./ret2win2/src/
    restart: unless-stopped
    ports:
      - 4006:6201
    networks:
      - magpiesctf2025
  expert1:
    privileged: true
    container_name: "expert1"
    build: ./expert1/src/
    restart: unless-stopped
    ports:
      - 4007:6201
    networks:
      - magpiesctf2025

networks:
  magpiesctf2025:
    driver: bridge
