services:
  flask:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py

  nginx:
    build:
      context: ./src
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flask