services:
  flask:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py

  nginx:
    build:
      context: ./src
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - flask
