services:
  ctf_service:
    container_name: jupyter
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "2222:2222"
    stdin_open: true
    tty: true
